### ISSUE TITLE
if project already exist (and not created with terraform) => error 401 already exist

### ISSUE THREAD

**Issue by flbla** [BESTSELLER/terraform-provider-harbor#39]
**Describe the bug**
If I create a project manually on Harbor, then add it to terraform, I get this error :
```
Error: [ERROR] unexpected status code got: 409 expected: 201
 {"errors":[{"code":"CONFLICT","message":"The project named test already exists"}]}
```

It could be great if it could check before if the project exist

**Comment by wrighbr** [comment]
Hi @flbla 
What you like terraform to do if there is already project named the same thing? The above error message comes from harbor itself.

if you like to import the project into terraform you can use the terraform import command or you could use the data resource

Cheers,
Brett

**Comment by flbla** [comment]
Hi @wrighbr,

The issue is if I create manually a project in Harbor (for eg: "test") for any reason,
Then I add it to my tfvars and do a terraform plan or apply, I get an error, that the project already exist in Harbor so it can't be created

It could be great, if the harbor provider could check if the project exist before try to create it.

**Comment by wrighbr** [comment]
Hi @flbla 

If you create a project manually in harbor then want to add it to terraform to (manage/modify/know about) the exist project. 
You will need to run the terraform import command.
https://github.com/BESTSELLER/terraform-provider-harbor/blob/master/docs/resources/project.md#import
```
terraform import harbor_project.main /projects/1
```

Otherwise you will need to delete the test project within harbor and then let terraform create the project

**Comment by flbla** [comment]
okay good, I didn't know that
thank you 😄
